from pathlib import Path
import unittest


class TestRepoLayout(unittest.TestCase):
    def test_repo_layout_smoke(self) -> None:
        root = Path(__file__).resolve().parents[1]

        required = [
            "README.md",
            "LICENSE",
            ".gitignore",
            "AGENTS.md",
            "docs/inspiration/action.pdf",
            "docs/setup_wsl.md",
            "docs/roadmap.md",
            "docs/architecture.md",
            "docs/cpmemu.md",
            "docs/cpm65_abi.md",
            "docs/acheron.md",
            "docs/bytecode.md",
            "docs/cpm65_cmdline.md",
            "docs/blockers.md",
            "docs/actc.md",
            "docs/spec.md",
            "docs/vm_abi.md",
            "docs/linker.md",
            "docs/real32.md",
            "docs/reu.md",
            "docs/overlays.md",
            "docs/vice.md",
            "src/compiler",
            "src/vm",
            "src/vm/vmhello/vmhello.asm",
            "src/vm/vmrun/vmrun.asm",
            "src/vm/vmrun/vm.c",
            "src/runtime",
            "src/runtime/modules",
            "src/runtime/modules/rt_reu_alloc.avo",
            "src/runtime/modules/rt_reu_free.avo",
            "src/runtime/modules/rt_reu_peek8.avo",
            "src/runtime/modules/rt_reu_peek16.avo",
            "src/runtime/modules/rt_reu_peek32.avo",
            "src/runtime/modules/rt_reu_poke8.avo",
            "src/runtime/modules/rt_reu_poke16.avo",
            "src/runtime/modules/rt_reu_poke32.avo",
            "src/runtime/modules/rt_reu_copy.avo",
            "src/runtime/modules/rt_ovl_load.avo",
            "src/runtime/modules/rt_ovl_call.avo",
            "src/runtime/modules/rt_f_add.avo",
            "src/runtime/modules/rt_f_sub.avo",
            "src/runtime/modules/rt_f_mul.avo",
            "src/runtime/modules/rt_f_div.avo",
            "src/runtime/modules/rt_f_cmp.avo",
            "src/runtime/modules/rt_i_to_f.avo",
            "src/runtime/modules/rt_f_to_i.avo",
            "src/runtime/modules/rt_print_f.avo",
            "src/runtime/modules/rt_print_str.avo",
            "src/runtime/modules/rt_print_line.avo",
            "src/runtime/modules/rt_format_int.avo",
            "src/tools_cpm",
            "src/tools_cpm/actc",
            "src/tools_cpm/actc/actc.c",
            "src/tools_cpm/hello/hello.asm",
            "src/tools_cpm/hello/hello.c",
            "tools/actionc64u_compile.py",
            "tools/actionc64u_link.py",
            "tools/avo_format.py",
            "tools/avm_pack.py",
            "tools/vice_harness.py",
            "tools/find_llvm_mos.sh",
            "tools/env_check.sh",
            "tools/setup_wsl.sh",
            "tools/path_probe.py",
            "tools/cpmemu_runner.py",
            "tools/build_cpm65_notes.sh",
            "tools/build_hello.sh",
            "tools/build_actc.sh",
            "tools/build_vmhello.sh",
            "tools/build_vmrun.sh",
            "tools/install_to_image.py",
            "pytest/__main__.py",
            "tools",
            "examples",
            "examples/hello.act",
            "examples/if.act",
            "examples/math.act",
            "examples/real_math.act",
            "examples/real_cmp.act",
            "examples/reu_demo.act",
            "examples/ovl_demo.act",
            "examples/hello.avm",
            "examples/hello.avm.txt",
            "tests",
            "tests/test_cpmemu_available.py",
            "tests/test_hello_com.py",
            "tests/test_vmhello.py",
            "tests/test_vmrun_file.py",
            "tests/test_compile_and_run.py",
            "tests/test_actc_on_target.py",
            "tests/test_compile_features.py",
            "tests/test_linker.py",
            "tests/test_real.py",
            "tests/test_reu_overlay.py",
            "tests/test_vice_smoke.py",
        ]

        missing = [path for path in required if not (root / path).exists()]
        self.assertFalse(missing, f"Missing required project paths: {missing}")


if __name__ == "__main__":
    unittest.main()
