from __future__ import annotations

import argparse
from pathlib import Path

FIXED_SERVICES = {
    "svc_get_abi_version": 0xCF00,
    "svc_console_write_sc0": 0xCF03,
    "svc_console_newline": 0xCF06,
    "svc_program_get_cmdline_ptr": 0xCF09,
    "svc_program_get_cmdline_len": 0xCF0C,
    "svc_program_exit": 0xCF0F,
    "svc_file_load_sc0": 0xCF12,
    "svc_dir_begin_current": 0xCF15,
    "svc_dir_next": 0xCF18,
    "svc_file_save_sc0": 0xCF1B,
    "svc_dir_make_sc0": 0xCF1E,
    "svc_dir_remove_sc0": 0xCF21,
    "svc_file_delete_sc0": 0xCF24,
    "svc_file_rename_sc0": 0xCF27,
    "svc_file_copy_sc0": 0xCF2A,
    "svc_file_write_begin_sc0": 0xCF2D,
    "svc_file_write_chunk_sc0": 0xCF30,
    "svc_file_write_close_sc0": 0xCF33,
    "svc_file_stage_reu_sc0": 0xCF36,
    "svc_reu_read_sc0": 0xCF39,
    "svc_reu_write_sc0": 0xCF3C,
    "svc_dir_begin_sc0": 0xCF3F,
    "svc_program_chain_sc0": 0xCF42,
}

FIXED_DATA = {
    "program_cmdline_buffer": 0xCF80,
    "dir_entry_buffer": 0xCDD0,
}

LABEL_HELPERS = {
    "svc_open_program_read_path_preserved": "tool_abi_open_program_read_path_preserved",
}

LABEL_CONSTANTS = {
    "udos_tool_abi_version": "ABI_VERSION",
}

FIXED_CONSTANTS = {
    "tool_file_status_fail": 0,
    "tool_file_status_ok": 1,
    "tool_file_status_too_large": 2,
    "tool_file_status_nofile": 3,
    "tool_file_status_exists": 4,
    "tool_dir_status_fail": 0,
    "tool_dir_status_ok": 1,
    "tool_dir_status_exists": 2,
    "tool_dir_status_nofile": 3,
    "tool_dir_status_not_empty": 4,
    "tool_dir_status_busy": 5,
    "tool_dir_status_flat": 6,
    "tool_dir_status_unmounted": 7,
    "tool_dir_status_bad": 8,
}


def load_ld65_labels(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    for line in path.read_text(errors="ignore").splitlines():
        parts = line.split()
        if len(parts) != 3 or parts[0] != "al":
            continue
        symbols[parts[2].lstrip(".")] = int(parts[1], 16)
    return symbols


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a UDOS service-address include from ld65 labels")
    parser.add_argument("--labels", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)

    labels = load_ld65_labels(Path(args.labels))
    # The exported UDOS tool ABI lives at fixed preserved addresses in the
    # launch-safe high-RAM area. We still require the labels file so the caller
    # has built UDOS, but we do not emit the lower-RAM resident addresses here.
    if not labels:
        raise SystemExit("missing expected UDOS labels; build the UDOS resident image first")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; autogenerated from UDOS resident labels",
        "; do not edit by hand",
        "",
    ]
    for name, addr in FIXED_SERVICES.items():
        lines.append(f"{name} = ${addr:04X}")
    lines.append("")
    for name, addr in FIXED_DATA.items():
        lines.append(f"{name} = ${addr:04X}")
    lines.append("")
    for public_name, label_name in LABEL_HELPERS.items():
        if label_name not in labels:
            raise SystemExit(f"missing expected UDOS label: {label_name}")
        lines.append(f"{public_name} = ${labels[label_name]:04X}")
    lines.append("")
    for public_name, label_name in LABEL_CONSTANTS.items():
        if label_name not in labels:
            raise SystemExit(f"missing expected UDOS label: {label_name}")
        lines.append(f"{public_name} = {labels[label_name]}")
    lines.append("")
    for name, value in FIXED_CONSTANTS.items():
        lines.append(f"{name} = {value}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
