from __future__ import annotations

import argparse
from pathlib import Path

SERVICES = [
    "svc_get_abi_version",
    "svc_console_write_sc0",
    "svc_console_newline",
    "svc_program_get_cmdline_ptr",
    "svc_program_get_cmdline_len",
    "svc_program_exit",
]

DATA_SYMBOLS = [
    "program_cmdline_buffer",
]


def load_ld65_labels(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    for line in path.read_text(errors="ignore").splitlines():
        parts = line.split()
        if len(parts) != 3 or parts[0] != "al":
            continue
        symbols[parts[2].lstrip(".")] = int(parts[1], 16)
    return symbols


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a UDOS service-address include from ld65 labels")
    parser.add_argument("--labels", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)

    labels = load_ld65_labels(Path(args.labels))
    missing = [name for name in SERVICES + DATA_SYMBOLS if name not in labels]
    if missing:
        raise SystemExit(f"missing service labels: {', '.join(missing)}")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; autogenerated from UDOS resident labels",
        "; do not edit by hand",
        "",
    ]
    for name in SERVICES:
        lines.append(f"{name} = ${labels[name]:04X}")
    lines.append("")
    for name in DATA_SYMBOLS:
        lines.append(f"{name} = ${labels[name]:04X}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
